### ISSUE TITLE
[feature request] Renaming stops displayed on the card

### ISSUE THREAD

**Issue by pvojnisek** [amaximus/bkk_stop#12]
I would like to rename the stop displayed on lovelace.

For example: Bem tábornok utca --> Bem stop

![bkk_stop Lovelace example](https://raw.githubusercontent.com/amaximus/bkk_stop/master/example/bkk_lovelace.jpg)

The `name` attribute could be used in the yaml like this:
```
type: custom:bkk-stop-card
entity: sensor.bkk_bem
name: Bem stop
```

**Comment by amaximus** [comment]
This is the custom integration. You should open a FR at https://github.com/amaximus/bkk-stop-card/issues
