### ISSUE TITLE
Displaying not rounded arrival informations in minutes

### ISSUE THREAD

**Issue by HeAtNet** [amaximus/bkk_stop#16]
Hello!

I updated this integration to the latest version (2.1.0), and now, the `in` parameters are containing a lot of decimal places.

Maybe this commit caused the problem, but I am really not sure:
https://github.com/amaximus/bkk_stop/commit/c57faa29a3f2966d271320c07b08e2ddcfdff94b
( `diff` changed to `str(diff)` )

![image](https://user-images.githubusercontent.com/22809785/150633504-c8d18de1-76d7-4d1f-9587-25efdce2b5db.png)
![image](https://user-images.githubusercontent.com/22809785/150633522-7d3b622d-8a4e-44e3-a5c9-dbc884da0a8c.png)

PS.: Thank you for this integration. Really helpful!

**Comment by amaximus** [comment]
Thanks for reporting this.

Just pushed a new release (2.1.1) fixing this bug.

Please update the component and get back to me with results.

**Comment by HeAtNet** [comment]
Everything works nicely. Thank you!
