### ISSUE TITLE
minsBefore

### ISSUE THREAD

**Issue by tamas-grosz-epam** [amaximus/bkk_stop#24]
Hi,
A suggestion: I guess the main use case is to check when to leave home to catch the next bus. That means the ones arriving earlier than the walking time to the station are not important. Probably the minsBefore parameter can be used for that (maybe with a negative value), so could you add this one? Alternatively, either in this component or in the lovelace card those routes may be discarded.

**Comment by amaximus** [comment]
Hi,

newly released version 2.9.0 adds a parameter to skip vehicles departing from the station while walking to the station.

Please upgrade the custom component, test it and get back to me with results.

Thanks.

**Comment by tgrosz** [comment]
Well, technically it's working - but why don't we use the service provided minsBefore parameter (with a negative value)? I tested it, and it works just like the minsAfter which we use.

**Comment by amaximus** [comment]
Now I see what you mean. Give me a couple of minutes.

**Comment by amaximus** [comment]
Just released version 2.9.1 with the proper modifications.

Please check on your side too and get back to me with results.

**Comment by tgrosz** [comment]
Yeah, that's it, thank you. And sorry for being very lazy and not making a PR, just asking for the extension

**Comment by amaximus** [comment]
No problem. Thanks for the request.
