### ISSUE TITLE
wrong timezone is displayed on the card

### ISSUE THREAD

**Issue by SturmUDrang** [amaximus/bkk_stop#25]
steps to reproduce: 
- server (or user running HA on the server) is in UTC while client browser is CET
- current time in CET is 23:45

card displays: 
... in 2 mins at 22:45

While the shown schedule is correct the displayed time is in UTC and not acourding to the TZ of the profile settings

**Comment by amaximus** [comment]
Trying to reproduce the issue:
* HASS time zone set to UTC (see sensor.date_time)
* the card displays times as per CEST timezone of the browser as shown in the attached screenshot
![bkk](https://github.com/amaximus/bkk_stop/assets/2511168/1cf6aea1-623c-4336-b464-d937d9eaa1b4)

**Comment by SturmUDrang** [comment]
Interesting, let me show mine,
`
pi@pi:/opt/homeassistant/config $ date -R
Thu, 02 Nov 2023 16:30:29 +0000

pi@pi:/opt/homeassistant/config $ docker exec ac6fbd372131 date -R
Thu, 02 Nov 2023 16:30:32 +0000
`

![image](https://github.com/amaximus/bkk_stop/assets/4864665/25f17dbf-b451-4097-8b00-f39c5ad7b20d)

HA seems to think that my timezone is Europe/Budapest, but as a matter of fact, as you can see from the shell output, it is not.
![image](https://github.com/amaximus/bkk_stop/assets/4864665/b09ef289-5aa9-4679-828d-b18b4155bc94)

Maybe it is a HA issue than?

**Comment by amaximus** [comment]
There is a difference between OS time zone, time zone set in HA configuration and time zone associated with your browser account.

**Comment by SturmUDrang** [comment]
I have changed the TZ to Budapest on OS level and it solved it. I still suppose this is a bug, albeit a minor one, because it does not take the user settings into account just displays the time in the OS timezone

**Comment by amaximus** [comment]
Relese 2.9.3 fixes this issue.

Please upgrade the component and get back to me with results.

**Comment by SturmUDrang** [comment]
Thanks, it works now

**Comment by amaximus** [comment]
Thanks for confirmation.
