### ISSUE TITLE
Still the minutesBefore :(

### ISSUE THREAD

**Issue by tamas-grosz-epam** [amaximus/bkk_stop#26]
Sorry, I think it's not a good idea to add the minus sign to the request.
The swagger says, both minutesBefore and minutesAfter set the relative time to server time. So, I'd set it in component config (minsBefore: -10) if I want to see only routes arriving after now(). Adding a minus sign there causes 2 issues actually: it won't work if someone sets a negative time in yaml and the parameter name and value won't be in sync. I see, that the parametes names in BKK service are simply misleading, something like 'from' 'to' would be better, but that's their problem.

**Comment by amaximus** [comment]
You don't have to put a negative value. minsBefore accepts non-negative value that is deducted from the current time.

**Comment by tamas-grosz-epam** [comment]
Ok, the problem is:
1. if I set a negative value in yaml config (as the bkk developers imagined), then it won't work now because the request has a burned in minus sign (so that the request will be like minutesBefore=**--**10 which won't be valid
2. the other is not so important, but still bkk developers imagined that we should use the negative values for later time and we do the opposite now

**Comment by amaximus** [comment]
Release 2.9.2 now follows BKK Go's usage on minsBefore.

**Comment by tamas-grosz-epam** [comment]
thanks
