### ISSUE TITLE
Add manual update action

### ISSUE THREAD

**Issue by mrbaloghakos** [amaximus/bkk_stop#29]
The refresh time would ideally be 1 second or realtime, but obviously it is not possible. When I'm on the way to the stop, the data in HA can be outdated and I have to check the BKK app for delays, so the integration loses its purpose for me 

Please add:
- a boolean in the config, that enables auto refreshing (default to true)
- a Home Assistant integration action, that updates the integration manually when calling it

Thanks.
Great work btw!

**Comment by amaximus** [comment]
@mrbaloghakos newly release version 2.10.0 adds actin for instant refresh.

The bkk-stop-card will be updated soon to have a refresh button.

I will keep you posted.

**Comment by amaximus** [comment]
New version of the BKK Stop Card adds a button for instant refresh.

Please check on your side too and get back to me with results.

**Comment by mrbaloghakos** [comment]
**🔴  When clicking on the refresh button, an error appears in the log:**
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bkk_stop/sensor.py:202
integration: bkk_stop (documentation, issues)
First occurred: 2:36:58 PM (1 occurrences)
Last logged: 2:36:58 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bkk_stop/sensor.py", line 202, in extra_state_attributes
    self._state = bkkjson["vehicles"][0]["in"]
                  ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```


**🔴  The button on the card is not configured properly for dark mode:**
<img width="570" alt="SCR-20241125-nbmb-2" src="https://github.com/user-attachments/assets/f85edaea-4798-409a-a24b-2e1bb07c33a7">

🔵 **Would be nice:**
- A spinner while reloading
- A visual effect that confirms the click/tap (eg.: it could turn to green for a second, then fade to the original color)

**Comment by amaximus** [comment]
Have you updated the custom integration and restarted? That adds support for he service call the button press invokes.

**Comment by mrbaloghakos** [comment]
Yes, I have updated both the component and the card. Then I have restarted. Still getting the mentioned errors, also in an incognito tab.
```
Core - 2024.11.3
Supervisor - 2024.11.4
Operating System - 13.2
Frontend - 20241106.2
```

**Comment by amaximus** [comment]
Both the integration and the card have been updated to address the issues:
* fix the reported error message
* refresh button's color to use theme's colors

* there is no point for adding a spinner while loading as the reload is instant
* there is no point for adding visual effect on click as it's instant and the result is also instant (times get updated).

**Comment by mrbaloghakos** [comment]
I can confirm both the integration and the card working properly with the latest update. 
Thanks a lot! 🚀
