### ISSUE TITLE
Characters coding issue

### ISSUE THREAD

**Issue by peetereczek** [amaximus/bkk_stop#7]
I found recently, that characters coding is wrong for BKK information:

![image](https://user-images.githubusercontent.com/42431204/74637232-de3a4c80-5169-11ea-9ba9-2269e09f2c05.png)
![image](https://user-images.githubusercontent.com/42431204/74637258-eb573b80-5169-11ea-846b-03cfe7e2d85d.png)

Is there any possibility to fix it?

**Comment by kovlo** [comment]
The problem exists in the Futár app and on their webpage too:
![Screenshot from 2020-02-17 09-48-27](https://user-images.githubusercontent.com/12111565/74637696-c1eadf80-516a-11ea-8762-c4055e9f13a5.png)

**Comment by peetereczek** [comment]
Ok, so problem is not related to that plugin

**Comment by amaximus** [comment]
Changed character encoding issue solved on the custom component.
