### ISSUE TITLE
Display the exact hour and minute of arrival

### ISSUE THREAD

**Issue by Dilergore** [amaximus/bkk_stop#8]
Hi,

I would like to request a feature to have an option (bool) to enable displaying the hour and minute of arrival like:
14 to Lehel Tér M in 8 mins **at 10:05**

Thanks!

p.s.: This issue might belong to the other repo where you store the Lovelace card.

**Comment by amaximus** [comment]
Added exact hour:min of departure time to the latest release.
Also updated the bkk-stop-card with two configuration parameters to select which information to be displayed: in_minutes and/or at_time.

Please update the custom platform and the custom card as well and get back to me with results.

**Comment by Dilergore** [comment]
Thanks! It is working.

**Comment by amaximus** [comment]
Thanks for the feedback.
